"""Generate the synthetic historical dataset.

Run once after install:

    python -m scripts.generate_synthetic_history

This data is SYNTHETIC; generated by a random walk model, not real market
data. It is used solely to demonstrate that the backtest pipeline runs
end-to-end. See README.md for details.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.synthetic_data import generate


def main() -> None:
    print("Generating synthetic historical dataset...")
    print("This data is synthetic, NOT from real markets.")
    summary = generate(seed=42)
    print()
    print(f"  games:            {summary['games']}")
    print(f"  kalshi snapshots: {summary['kalshi_snapshots']}")
    print(f"  odds snapshots:   {summary['odds_snapshots']}")
    print(f"  synthetic 'now':  {summary['synthetic_now']}")
    print()
    print("Written to data/trades.db")


if __name__ == "__main__":
    main()
